### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dfinke** [microsoft/prompts-for-edu#1]
Really glad to see these prompts published.

Very curious about `Deploy in Azure` in the markdown files. Would like to learn more so I can set these up for my prompts.

Thank you.

![image](https://github.com/microsoft/prompts-for-edu/assets/67258/7517e964-ef1c-4608-89de-3c207e8dc84b)

**Comment by cricex** [comment]
Hi @dfinke , we'll be adding this functionality soon. It will be based on the built-in Deploy to WebApp functionality in Azure OpenAI Studio, which is based on this repo: https://github.com/microsoft/sample-app-aoai-chatGPT
